title: KISS
description: Documentation for the KISS Project
# url: "https://yolij.github.io/kiss-docs-gh1/docs" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Deltares":
    - "https://www.deltares.nl/nl/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
